### ISSUE TITLE
Гыгыгы где 7 лаба, Аметов? Это же твой любимый предмет! :confetti_ball: 

### ISSUE THREAD

**Issue by luk-chesnok-xren** [remr2005/DataAnalys8lab#1]
ГЫГЫГЫ, Где седмая лаба, Аметов? Это же твой любимый предмет! :confetti_ball: 
![Снимок экрана от 2024-10-15 10-04-33](https://github.com/user-attachments/assets/27e177e3-9efa-4476-b1ac-c9cf5aa69534)

**Comment by remr2005** [comment]
уже бегу
